### ISSUE TITLE
ARISA_FIX_CAPITALIZATION does not validate argument

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#587]
## The Bug
The command `ARISA_FIX_CAPITALIZATION` has an argument which is not validated at all. The [wiki](https://github.com/mojira/arisa-kt/wiki/Commands#arisa_fix_capitalization) says the command is `ARISA_FIX_CAPITALIZATION description`, but you can actually run it with any argument, e.g.:
```
ARISA_FIX_CAPITALIZATION does_not_matter_at_all
```

## Expected behavior
It would be good to validate that the argument is `description` and otherwise thrown an exception.
Otherwise one might use `ARISA_FIX_CAPITALIZATION summary` and then wonder why the command fails, or why it updated the description.

**Comment by chandler05** [comment]
The reason I implemented it as such nos because I don't think it's possible to create a command without ba required argument, or I didn't know how to :/ a better solution would be to remove the requirement for the argument entirely

**Comment by Marcono1234** [comment]
Yes the current logic requires that a command contains at least one space (which will still be the case after the changes done by  #586), possibly to prevent ambiguity with 'tags' such as `ARISA_NO_DUPLICATE_MESSAGE`?

Personally I am fine with keeping the current logic requiring an argument for now, though it would be good to validate the argument then to prevent any confusion (as described in this issue).

**Comment by violine1101** [comment]
I think I actually got rid of the required argument in #579, so it technically still exists but isn't used at all (see [here](https://github.com/mojira/arisa-kt/commit/45208d50db5a9efaabd6da10cc89c57e36b0347e#diff-b5a032e5c063e40dd8f20504b551ed12e921bb82ad4540ba87a4c08a643fbad8R108)). However commands still need to contain whitespace... so yeah that's what the current behaviour is.

I'm not really sure whether it'd make sense to remove the whitespace. There still should be some way to distinguish arisa commands from just flags.

Perhaps we should change the prefix for commands to something like `$ARISA` instead of just `ARISA`? Then we could be sure that every comment (line) starting with that is a command and not something else.
