### ISSUE TITLE
Resolve tickets about crashes as AR if no crash report is included

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#66]
If someone creates a ticket about a crash (the ticket includes the word "crash" or "crashes"), but there is no crash report (crash report attachment, launcher log attachment, hs_err_pid attachment or parts of a crash report) in the ticket, the bot should automatically resolve the ticket as Awaiting Response and post a message telling the reporter to attach the crash report (or launcher log, or hs_err_pid file).

False positives should be avoided, so perhaps the check should be a bit more sophisticated than that.

**Comment by Marcono1234** [comment]
False positives might indeed be an issue, for example when the reporter writes:
- "..., but no crash report was created"
- "..., but it did not crash"

Though since the reports are only resolved as "Awaiting Response" and are reopened automatically when the reporter responds, the damage created by false positives is not that great.

**Comment by NeunEinser** [comment]
It also only should resolve "open" issues, not ones that are already "reopened"

**Comment by chandler05** [comment]
Maybe this could detect if the user gave the issue a tag of "crash" instead of just searching for the word crash in the report. That would potentially avoid a lot of false positives because the only reason a user would give it that tag is because it is an actual crash.

**Comment by NeunEinser** [comment]
There are currently only 26 issues from all issues that were ever reported that match the query `project = MC AND labels = "tag"`. I doubt that would be any useful.

**Comment by NeunEinser** [comment]
I would not assume such things.
[MC-191618](https://bugs.mojang.com/browse/MC-191618) - no idea why this has the label crash.
[MC-185092](https://bugs.mojang.com/browse/MC-185092) - about a world saving bug that happened due to a crash in the OS they were using - no crash report expected here
[MC-184072](https://bugs.mojang.com/browse/MC-184072) - no idea

That's just some of the first issues that contained said label that I looked at. In general, I would not assume anything about what people do who are reporting bugs :D

**Comment by chandler05** [comment]
If those were resolved as AR, a user or the reporter could comment on it to reopen it. Detecting the word crash doesn't seem like as  big of an issue as #347 because any user who sees that the report gave false positives could comment on it to reopen it. (Unless #353 is implemented)

**Comment by NeunEinser** [comment]
Yes, I was just illustrating that only working on reports with the "crash" label doesn't solve the problem and we are probably better off not requiring it, as most users don't add labels when creating an issue.
